### ISSUE TITLE
Created Bug Report for Current Bugs

### ISSUE THREAD

**Issue by JerJohn15** [codeforboston/cambridge_energy_app#102]
Hey everyone, 

Since I've successfully been able to configure my environment, so that I can run this project in my local web browser, I have been performing manual tests for the current features that we have so far, at the time of this post being created, and documenting them in a Bug Report. To download  it see
[cambridge energy app bug report.zip](https://github.com/codeforboston/cambridge_energy_app/files/247153/cambridge.energy.app.bug.report.zip). (If you cannot see the images very well, open the _doc_ file in Word, or whatever software you have that can open and edit _doc_ files, select that images and adjust it to a size that is visible to you.) 

Just so there is no confusion with what each category means in the tables, in the document, I've included a breakdown of each category (Note: The _Troubleshooting_ section does not contain the solution but rather details the attempts taken to workaround the issue.).

I have not attempted to troubleshoot any of these bugs, at the moment (this is why some fields in the document are blank), my goal right now is just to spot and document as many bugs as I can find, so this report will be updated, as I find more. 

Someone please let me know if any of the issues in the documents need further clarification. Also, if anyone wants to add their own issues, or use this report as a template to create your own, feel free to.

**Update:**
- Added Bug's 16 and 17 - May 2nd
- Updated Bug Report to reflect latest bug fixes   - May 3rd

**To Do:**
- [X] Cannot sign in with Google - Bug 1
- [x] 550 Page error shown when inviting team mates - Bug 2
- [x]   [Show Images for user's team](https://github.com/codeforboston/cambridge_energy_app/issues/103) - Bug 3
- [x]  [ Existing user invites](https://github.com/codeforboston/cambridge_energy_app/issues/104) - Bug 4
- [x]  [Send Reset Instructions gives error](https://github.com/codeforboston/cambridge_energy_app/issues/105) - Bugs 5, 14
- [x]  ["back" buttons generally badly functioning](https://github.com/codeforboston/cambridge_energy_app/issues/108) - Bugs 6, 8 
- [x] [Unit creation error](https://github.com/codeforboston/cambridge_energy_app/issues/107) - Bug 7
- [X] [ destroys a team regardless if the deleting user owns that team](https://github.com/codeforboston/cambridge_energy_app/issues/100)
- [x] [When deleting a team postgres issue](https://github.com/codeforboston/cambridge_energy_app/issues/99) - Bug 9
- [X] Team member can see other team names - Bug 10
- [X] [Cannot access profile on live site](https://github.com/codeforboston/cambridge_energy_app/issues/110) - Bug 12 
- [X] [Phone validation](https://github.com/codeforboston/cambridge_energy_app/pull/115) - Bug 13 (also see #129)
- [x] [cannot create bill while logged in on live site](https://github.com/codeforboston/cambridge_energy_app/issues/111) - Bug 15
- [x] Email address for inviting teammate should be verified - Bug 16
- [x] [Access denied message shown](https://github.com/codeforboston/cambridge_energy_app/issues/134) - Bug 17

**Comment by mzagaja** [comment]
Hi @JerJohn15, thanks so much for documenting these bugs. I definitely want to encourage anyone who works on these to create individual issues for the bug they are working on so people know you are working on it and we avoid duplicating work.

**Comment by JerJohn15** [comment]
Sure thing. I don't know when I'll start looking at solving these issues (I need to learn Ruby first and look through the project), but whenever, I do, I will notify people which one(s) I'm working on. 

We should probably, at some point in the near future, consider using a project management tool (a free one ideally), as it'll make monitoring tasks and issue tracking less complicated. 

Note: I've updated my bug report, see my original post for details.

**Comment by itiswicked** [comment]
Hey @JerJohn15, what management tools do you use? I'm familiar with trello and pivotal tracker, but I'm always interested in other recommendations.

**Comment by JerJohn15** [comment]
Well, I've only used Pivotal Tracker and, most recently, Producteev but both just served a need  for documenting logs for individual projects I had been working on. I haven't used any PM tools in an actual team environment.  

I did do some research into what exists out there, and so far I am impressed with [zenhub](https://www.zenhub.io/) because  it is integrated within GitHub's UI, not as a separate product you need to download/ install  nor a  third party website with it's own UI you need to access. I'm still playing around with it, but so far it doesn't seem difficult to learn if your comfortable with using GitHub already. You can also check out their [blog](https://www.zenhub.io/blog/) for more insight into their product. 

Other tools I had been looking at were [waffle.io](https://waffle.io/) and [overv](https://overv.io/). I was trying to find a tool that integrates with GitHub's Issue's section, since we are currently using it. You, and others, can let me know what you think.

**Comment by mzagaja** [comment]
Zen hub looks promising to me. I like tools that integrate with GitHub issues. It is my understanding that Other Code for Boston projects have used waffle.io. I will ask the other project leads for input on these tools and they may comment here with their experiences, and then I think we can arrive at a consensus. Thanks so much for doing research into this @JerJohn15.

**Comment by mzagaja** [comment]
2 and 15 should be fixed by adding SendGrid credentials to the live site which I just did. 16 should be fixed in #176. Thanks for documenting all of these!
