### ISSUE TITLE
Go List for EnerSave Launch

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#310]
- [x] Need image assets from City of Cambridge
- [x] Need to integrate front end design into rails app #294 #262 #265 #264 
- [x] Change upload XML file into Upload Green Button Data #277 
- [x] Merge existing pull requests
- [x] Fix logout bug #299 
- [x] Explain how team scores work and teams
- [x] Get a free home energy assessment is the main thing to promote - How to win? MassSave.com is the link to use for that.
- [x] Add invite to team URL on the team page
- [x] Fix invite to team #268 #295 #306
- [x] Need specifications for the prizes and to explain how it works
- [x] Explain how team scores work. #309
